### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Nelliza** [IgorSushko1/IgorSushko-Test-frontend-2step-FSD#1]
Нужно добавить в файл README.md команды для клонирования проекта, установки пакетов, запуска dev-сервера и сборки production версии

**Comment by IgorSushko1** [comment]
Добавил. Настроил dev server и production

**Comment by Nelliza** [comment]
Команду для клонирования репозитория не добавил )

**Comment by Nelliza** [comment]
Еще сразу просьба: в названиях коммитов с правками по конкретным issues указывай плиз ссылку на номер issue примерно таким образом: [название коммита] [#номер issue]. Например, в твоем случае это будет коммит "Добавлены production и development моды #1". Это облегчает и ускоряет проверку, т.к. внутри самого ишью становится наглядно видно, какие правки были внесены применительно к нему

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/71324566-444f7e00-24f1-11ea-963e-dacc16c9dce8.png)

Всю лишнюю информацию, не указанную в [стандартах](https://github.com/fullstack-development/front-end-best-practices/blob/master/Initiation.md), следует удалить из файла

**Comment by Feinminen** [comment]
Необходимо ещё указать все нестандартные библиотеки. Как минимум, в проекте есть ion-rangeslider и air-datapicker.
Желательно вообще все либы указать, примерно вот так :)
![image](https://user-images.githubusercontent.com/44312820/72659013-b087a980-39eb-11ea-9ad2-fab4ed0571b2.png)
