### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Nelliza** [IgorSushko1/IgorSushko-Test-frontend-2step-FSD#2]
Не стоит использовать в разметке тег `<br>` без острой необходимости. Например, если тебе нужен отступ между элементами, добиться его можно с помощью CSS-правил, не прибегая к добавлению лишних элементов в разметке

**Comment by Nelliza** [comment]
Все атрибуты в pug-файлах должны быть внутри двойных кавычек

**Comment by Nelliza** [comment]
Также следует удалить все лишние комментарии в коде и выводы на консоль

**Comment by IgorSushko1** [comment]
Комментарии убрал

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/69900211-af3de700-1381-11ea-8880-c79c5b79b994.png)
Здесь также нет необходимости в теге `<br>`

**Comment by Nelliza** [comment]
> Не нашел атрибуты не в двойных кавычках. Они и не работали бы без кавычек.

Имелось в виду использование двойных кавычек вместо одинарных в pug-файлах.
Здесь же следует сразу исправить наоборот двойные кавычки на одинарные в scss- и js-файлах

**Comment by Nelliza** [comment]
> Комментарии убрал.

Не похоже на то )
![2](https://user-images.githubusercontent.com/19621113/69900267-40ad5900-1382-11ea-9219-24a9ebef265f.png)

**Comment by Nelliza** [comment]
Та же ситуация и с выводами на консоль
![3](https://user-images.githubusercontent.com/19621113/69900283-5fabeb00-1382-11ea-8ac0-0e2d84615121.png)

**Comment by Nelliza** [comment]
> Все атрибуты в pug-файлах должны быть внутри двойных кавычек

Опять не везде заменил, в файле **ui-kit.pug** посмотри

**Comment by Nelliza** [comment]
> Имелось в виду использование двойных кавычек вместо одинарных в pug-файлах.
> Здесь же следует сразу исправить наоборот двойные кавычки на одинарные в `scss`- и `js`-файлах

Опять не везде убрал, в файле **ui-kit.pug** посмотри, в `scss`-файлах тоже много где двойные остались

**Comment by IgorSushko1** [comment]
Заменил кавычки кроме js файлов относящихся к плагинам календаря и слайдера

**Comment by Feinminen** [comment]
Остались ещё комментарии. Нужно проверить по всему проекту.
![image](https://user-images.githubusercontent.com/44312820/76375896-81e9d780-6379-11ea-8cd5-ebb3ca60762e.png)
