### ISSUE TITLE
Не использовать id

### ISSUE THREAD

**Issue by Nelliza** [IgorSushko1/IgorSushko-Test-frontend-2step-FSD#4]
В верстке довольно много где встречаются id-шники, использования которых следует избегать ([п.10 HTML-стандартов](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/tags.md))

**Comment by IgorSushko1** [comment]
Убрал id во всех файлах, кроме выпадающего списка - на классах неудобно переписывать плагин.

**Comment by IgorSushko1** [comment]
Переписал выпадающий список на классы. Теперь в коде нет id

**Comment by Nelliza** [comment]
> Переписал выпадающий список на классы. Теперь в коде нет id

![4](https://user-images.githubusercontent.com/19621113/69900608-b4e9fb80-1386-11ea-8daf-dd6de93c6336.png)
![5](https://user-images.githubusercontent.com/19621113/69900609-b74c5580-1386-11ea-85b2-1458ee799a03.png)
Есть еще много где в коде, посмотри внимательно по всему проекту

**Comment by Nelliza** [comment]
От id-шников для календарей также следует избавиться, у нас [в стандартах (п. 10)](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/tags.md) содержится исчерпывающий перечень случаев, когда использование id имеет смысл:
![1](https://user-images.githubusercontent.com/19621113/71323968-5e399280-24ea-11ea-98b5-dd2655000a48.png)

**Comment by IgorSushko1** [comment]
Избавился от всех id, кроме тех, что вызываются для календаря  -- использование id в календаре является пунктом инструкции его автора.
