### ISSUE TITLE
Реализовать автоматический импорт файлов

### ISSUE THREAD

**Issue by Nelliza** [IgorSushko1/IgorSushko-Test-frontend-2step-FSD#5]
Следует реализовать в точке входа автоматический импорт всех стилевых и js-файлов, чтобы каждый раз при подключении или переносе файлов не вносить правки вручную

**Comment by IgorSushko1** [comment]
Я не понял :) все файлы складываются в dist и работают с файлами в своём окружении. Еще отвязал все импорты в index.js от node_modules - теперь пакеты используются только вэбпаком, только при билде.

**Comment by Nelliza** [comment]
Смотри, вот этого быть не должно:
![1](https://user-images.githubusercontent.com/19621113/69901226-00ed6e00-1390-11ea-9ea3-76a5f641f366.png)
![2](https://user-images.githubusercontent.com/19621113/69901236-02b73180-1390-11ea-8bb6-1e2807f63909.png)
![3](https://user-images.githubusercontent.com/19621113/69901237-0480f500-1390-11ea-9e10-86bc2cab7c23.png)

Дальше больше того - файлов **style.scss** и **overall.scss** в принципе быть не должно )

**Comment by IgorSushko1** [comment]
я искренне не понимаю почему это плохо, и как сделать хорошо. Допустим я использую require.context. Он всё равно потребует импортов, но уже во множестве файлов. У меня импорты в одном файле - их удобно модернизировать и поддерживать.

**Comment by IgorSushko1** [comment]
Возможен ли компромисс?) допустим, файлы со шрифтами и цветами я сделаю в каталоге повыше - чтобы они загружались первыми, а все остальные оставлю как есть - чтобы они подгружались после файлов с общими переменными(например такими как `$purple: #BC9CFF;`)?

**Comment by IgorSushko1** [comment]
Не получилось, всё таки require.context работает с каждым файлом в отдельности, но я задал вопрос на stackoverflow, вдруг кто знает как объединить файлы после require.context и до работы лоадеров))

**Comment by Nelliza** [comment]
> я искренне не понимаю почему это плохо, и как сделать хорошо. Допустим я использую require.context. Он всё равно потребует импортов, но уже во множестве файлов. У меня импорты в одном файле - их удобно модернизировать и поддерживать.

А как насчет реюзабельности компонентов? Миксины должны подключаться в местах своего использования, так ты можешь легко "выдернуть" любой компонент вместе со всеми его зависимостями

Так что повторюсь, нужно настроить также автоматический импорт стилевых файлов

**Comment by IgorSushko1** [comment]
Не знаю насколько грамотно, но по сути единственные заимствованные стили  во множестве стилевых файлах, которые относятся к элементам и блокам -- это цветовое решение дизайна страниц. 
Для загрузки цветов и всех scss файлов я использовал node-sass-glob-importer
В src/style.scss прописаны импорты папок в нужном порядке -- сначала цвета и шрифты,потом assets, дальше всё остальное

Мне казалось что я могу использовать эту же систему в любом другом проекте. Т.е. я всегда буду знать что в проектах есть такая система загрузки файлов, и что при копировании элементов и блоков мне надо будет скопировать и первые две папки

**Comment by Feinminen** [comment]
В итоге в любом случае нужно будет настроить автоматический импорт стилевых файлов)
Вопрос в том, почему необходимо импортить файлы в определённом порядке, чтобы всё работало адекватно?





> Мне казалось что я могу использовать эту же систему в любом другом проекте. Т.е. я всегда буду знать что в проектах есть такая система загрузки файлов, и что при копировании элементов и блоков мне надо будет скопировать и первые две папки с цветами и шрифтами


Если над проектом работает один разработчик - то это ещё имеет место быть. Но обычно над проектом целая работает команда разработчиков, а поддерживать проекты вполне может и другая команда. И каждый отдельный разраб должен понимать почему должна быть именно такая последовательность импортов. Это почти как навязывание собственно архитектуры проекта.

**Comment by IgorSushko1** [comment]
> Вопрос в том, почему необходимо импортить файлы в определённом порядке, чтобы всё работало адекватно?

Привет! Спасибо что посмотрел!

Необходимо поскольку если в каком то файле переменная, и её нет в этом файле, то  node-sass-glob-importer будет искать эту переменную в уже подгруженных файлах, т.е. он посмотрел один файл, посмотрел второй, нашел во втором файле переменную, а т.к. у него всего два файла в данный момент, то он идет в первый, проверяет наличие переменной, и если её нет, то забивает на неё и идет дальше. Я пробовал не указывать порядок загрузки папок, но в этом случае  node-sass-glob-importer начинал подгружать переменные только после загрузки файла с переменными, а раннее обнаруженные файлы где необходимо поставить переменную он не трогал.

**Comment by Feinminen** [comment]
Тут ещё нюанс в том, что лучше файлы с переменными напрямую импортить в файл где они используются. Чтобы можно было найти откуда вообще эта перменная взялась и что в ней лежит.
Т.е. на данном проекте лучше убрать node-sass-glob-importer, а все файлы с перменными прокиывать напрямую туда где они нужны и сделать автоматический импорт непосредственно через webpack. (к requireJS(require.context('./', true, /\.js$/)); просто добавить scss расширение)
